
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "numSExp : ExpExp : Termo Exp2Exp2 : '+' Termo Exp2Exp2 : '-' Termo Exp2Exp2 : Termo : Fator Termo2Termo2 : '*' Fator Termo2Termo2 : '/' Fator Termo2Termo2 : Fator : '(' Exp ')'Fator : num"
    
_lr_action_items = {'(':([0,5,8,9,11,12,],[5,5,5,5,5,5,]),'num':([0,5,8,9,11,12,],[6,6,6,6,6,6,]),'$end':([1,2,3,4,6,7,10,14,15,16,17,18,19,20,21,22,],[0,-1,-5,-9,-11,-2,-6,-5,-5,-9,-9,-10,-3,-4,-7,-8,]),'+':([3,4,6,10,14,15,16,17,18,21,22,],[8,-9,-11,-6,8,8,-9,-9,-10,-7,-8,]),'-':([3,4,6,10,14,15,16,17,18,21,22,],[9,-9,-11,-6,9,9,-9,-9,-10,-7,-8,]),')':([3,4,6,7,10,13,14,15,16,17,18,19,20,21,22,],[-5,-9,-11,-2,-6,18,-5,-5,-9,-9,-10,-3,-4,-7,-8,]),'*':([4,6,16,17,18,],[11,-11,11,11,-10,]),'/':([4,6,16,17,18,],[12,-11,12,12,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'SExp':([0,],[1,]),'Exp':([0,5,],[2,13,]),'Termo':([0,5,8,9,],[3,3,14,15,]),'Fator':([0,5,8,9,11,12,],[4,4,4,4,16,17,]),'Exp2':([3,14,15,],[7,19,20,]),'Termo2':([4,16,17,],[10,21,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> SExp","S'",1,None,None,None),
  ('SExp -> Exp','SExp',1,'p_Sexp','exp_sin.py',5),
  ('Exp -> Termo Exp2','Exp',2,'p_Exp','exp_sin.py',11),
  ('Exp2 -> + Termo Exp2','Exp2',3,'p_Exp2_add','exp_sin.py',15),
  ('Exp2 -> - Termo Exp2','Exp2',3,'p_Exp2_sub','exp_sin.py',19),
  ('Exp2 -> <empty>','Exp2',0,'p_Exp2_empty','exp_sin.py',23),
  ('Termo -> Fator Termo2','Termo',2,'p_Termo','exp_sin.py',28),
  ('Termo2 -> * Fator Termo2','Termo2',3,'p_Termo2_mult','exp_sin.py',32),
  ('Termo2 -> / Fator Termo2','Termo2',3,'p_Termo2_div','exp_sin.py',36),
  ('Termo2 -> <empty>','Termo2',0,'p_Termo2_empty','exp_sin.py',40),
  ('Fator -> ( Exp )','Fator',3,'p_Fator_exp','exp_sin.py',45),
  ('Fator -> num','Fator',1,'p_Fator_num','exp_sin.py',49),
]
